[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2021"

[profile.release]
# debug = true #necessary for https://github.com/flamegraph-rs/flamegraph
