[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]


[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[profile.release]
debug = true #necessary for https://github.com/flamegraph-rs/flamegraph
